# Site settings
title: mahasti
header-img: img/home-bg.png
email: mahasti110@yahoo.com
copyright_name: mahastihaghighi
description: > # this means to ignore newlines until "baseurl:"
  main
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mahastihaghighi
learn_profile: mahastihaghighi
email_username: mahasti110@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
